name=AS5040
version=0.1.0
author=Federico D. Ceccarelli <fededc88@gmail.com>
maintainer=Federico D. Ceccarelli <fededc88@gmail.com>
sentence=AMS AS5040 magnetic rotary encoder library
paragraph=The AS5040 software has been developed to allow SPI communication with a AMS AS5040 magnetic encoder.
category=Sensors
url=https://github.com/fededc88/AS5040.git
architecture=avr
inlcudes=AS5040.h
